### ISSUE TITLE
How to connect remx with react router?

### ISSUE THREAD

**Issue by nuttikung** [wix/remx#43]
I think this is an important part to integrate for react app, Could you please give me an example?

**Comment by andykog** [comment]
@nuttikung, there shouldn't be any issues, you can check this example of using mobx & react-router: https://github.com/gothinkster/react-mobx-realworld-example-app/blob/master/src/components/App.js
for remx everything is the same in this regard, just use `remx.connect(component)` instead of `@mobx.observer` decorator…
Feel free to reopen if you have some issues
